### PR TITLE
[#31420] Edit Vocabulary

### PR DESCRIPTION
**Pull request by bd-viget**
# Summary

This PR mostly wraps up the Edit Vocabulary functionality, allowing you to:

* Edit the Preferred Term
* Set an Alternate Term as the Preferred Term
* Add, Edit, Delete Alternate Terms
* Add, Edit, Delete Sources
* Add and Delete Categories
* ~~Set Category as Primary **(this doesn't update correctly in the DB, and the breadcrumbs won't update until the page is refreshed)**~~ This is out of scope, and is part of [#31418](https://app.shortcut.com/snac/story/31418/set-category-for-vocabulary-concept)

## Issues

* [#31420](https://app.shortcut.com/snac/story/31420/edit-a-vocabulary-term)
* [#31417](https://app.shortcut.com/snac/story/31417/change-an-alternate-term-to-a-preferred-term)
* [#31421](https://app.shortcut.com/snac/story/31421/delete-alternative-vocabulary-term)

## Testing Instructions

1. Login with editor capabilities
2. Click Edit on a Concept
3. Make Changes
4. Click Done Editing when satisfied

### CODE REVIEW

**Comment by bd-viget** [comment]
@nevinsm Just noticed some regression on some of the terms stuff, so going to go back, rebase, and double-check the stuff already merged into `development`.

**Comment by jglass-st** [comment]
Looking pretty good. I can confirm this satisfies [#31417](https://app.shortcut.com/snac/story/31417/change-an-alternate-term-to-a-preferred-term)

The following actions work great:
✅ Edit the Preferred Term
✅ Set an Alternate Term as the Preferred Term
✅ Edit Alternate Terms
✅ Add, Edit, Sources
✅ Add and Delete Categories

But these ones do not in this branch. A few of them are working on development, so you're probably aware of the regression.
❌ Add, Delete Alternate Terms
❌ Delete Sources
❌ Set an Alternate Term as the Preferred Term

Those not-working actions might just be a lacking a button or UI interface, or there could be a bit of api work needed still.

**Comment by bd-viget** [comment]
@jglass-st Just pushed up a few adjustments to fix some of the non-working items:

- [ ] Add Alternate Terms
https://github.com/user-attachments/assets/e98284e2-4f7c-4370-8959-e76f1f963cef
- [ ] Delete Alternate Terms
https://github.com/user-attachments/assets/3ba48f26-0a01-4fb8-9e33-96c9512c2b6c
- [ ] Delete Sources
https://github.com/user-attachments/assets/4c8b1aa7-3611-42c5-af3e-923ddca8e2bd
- [ ] Set an Alternate Term as the Preferred Term
https://github.com/user-attachments/assets/5d27949a-eb47-420c-ae44-7a5e6bd14fbc

**Review by jglass-st — APPROVED** [review]
This looks great! Everything working, code is concise and readable. Term editing looks 100%.

**Pull request merged**
